plugins {
    alias(libs.plugins.android.application)
    id("io.github.ackeecz.plugin.build")
}

android {
    def appProperties = project.ext.appProperties

    namespace = 'cz.ackee.sample'

    compileSdk = 37

    defaultConfig {
        minSdk = 23
        targetSdk = 37
        applicationId = appProperties["package_name"]
        versionName = appProperties["version_name"]

        manifestPlaceholders.put("appName", "Gradle build")
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation(libs.android.appcompat)
}
