[versions]
android-appcompat = "1.8.0"
android-gradlePlugin = "9.4.1"
kotlin-dokka = "2.2.0"
mavenPublish = "0.37.0"

[libraries]
android-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "android-appcompat" }

# Build logic dependencies
android-tools-build = { module = "com.android.tools.build:gradle", version.ref = "android-gradlePlugin" }
mavenPublish-gradlePlugin = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "mavenPublish" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradlePlugin" }
kotlin-dokka = { id = "org.jetbrains.dokka", version.ref = "kotlin-dokka" }
mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }

# Convention plugins defined by this project
ackee-internal-publish = { id = "ackee.internal.publish" }
